[from-internal]
exten => _1XX,1,NoOp(Ramal ${EXTEN} - Tenant test.local)
 same =>      n,Dial(PJSIP/${EXTEN}.test.local,,tTwWgHhkKo)
 same =>      n,Hangup()

exten => *65,1,Ringing()
 same =>     n,Wait(7)
 same =>     n,Answer()
 same =>     n,MusicOnHold(default) 
 same =>     n,Hangup()

exten => 60,1,Answer()
 same =>    n,Queue(suporte) 
 same =>    n,Hangup()

exten => 61,1,Answer()
 same =>    n,Queue(financeiro) 
 same =>    n,Hangup()

; Hints (BLF)
exten => 101,hint,PJSIP/101.test.local&Custom:101.test.local
exten => 102,hint,PJSIP/102.test.local&Custom:102.test.local

exten => h,1,Hangup()
